module: src.client.agents 
parameters: 
  url: 
  headers:
    Content-Type: application/json
    Authorization: Bearer <% PUT-YOUR-OPENAI-KEY-HERE %>
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
