module: src.client.agents.MagenticOneHander
parameters:
  key: 
  model: gpt-4o
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
